AWSTemplateFormatVersion: 2010-09-09
Description: IAM Role to allow IAM users and systems in the infosec-prod AWS account to read contents of the infosec-isolated S3 bucket containing CloudTrail logs
Metadata:
  Source: https://github.com/mozilla/security/tree/master/operations/aws-cloudtrail-storage/infosec-prod_cloudtrail_s3_reader_role.yml
Resources:
  CloudTrailReaderPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Read CloudTrail S3 buckets
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:ListAllMyBuckets
              - s3:GetBucketLocation
            Resource: '*'
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:ListBucket*
            Resource:
              - arn:aws:s3:::mozilla-cloudtrail-logs
          - Effect: Allow
            Action:
              - s3:GetObject*
              - s3:ListMultipartUploadParts
            Resource:
              - arn:aws:s3:::mozilla-cloudtrail-logs/*
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::371522382791:root
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref CloudTrailReaderPolicy
      RoleName: Infosec-Prod-CloudTrail-Log-Reader
